### ISSUE TITLE
Generalize "Development Workflow" section of ReadMe

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/wimpo#28]
Currently, the "Development Workflow" section of the ReadMe is specific to Angular. We should generalize this to be applicable to all kinds of projects. We can consider adding specific sections or examples for certain types of projects, like Angular, Vue, backend services, etc.

**Comment by amedenblik** [comment]
Some examples that might be helpful?

https://github.com/USGS-WiM/streamstats#development-workflow
https://github.com/USGS-WiM/ss-weightingservices#development-workflow

**Comment by BlakeDraper** [comment]
Check if this looks done!
