### ISSUE TITLE
Update URL

### ISSUE THREAD

**Issue by ghost** [USGS-WiM/wimpo#34]
In `README.md`, change `https://github.com/USGS-WiM/wimfo/blob/dev/Development/wimpo_template_repository.md` to `https://github.com/USGS-WiM/wimfo/blob/dev/Development/Development_at_WIM/Application_Standards/wimpo_template_repository.md`

**Comment by lmash12** [comment]
hey can i work on this?

**Comment by ghost** [comment]
Thanks, @lmash12 ! We created this issue specifically as a training exercise for our new members to gain experience with GitHub, so we are going to save this issue for them to work through. We appreciate your willingness to help out, though!
